spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

jwt:
  token:
    secret: jwttoken
    expired: 3600000

upload:
  path: D:/java/techshop/images

aws:
  bucketName: astrofy
  region: us-east-2
  accessKeyId: AKIAZ3RB36W6OE7TFKF5
  secretAccessKey: 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

---
spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/springshop?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1234

